apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: buildversions
resources:
- configmap.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- persistentvolumeclaim.yaml
- secret.yaml
