#https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
#https://docs.k3s.io/storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildversionsapi-claim
  namespace: buildversions
spec:
  accessModes:
    # - ReadWriteOnce
    - ReadWriteMany 
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: buildversionsapi-volume
  # labels:
  #   type: local
  #   app: buildversionsapi
spec:
  # storageClassName: manual
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    # - ReadWriteOnce
    - ReadWriteMany 
  hostPath:
    path: "/tmp/shared/buildversionsapi"
