apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-volume
  #labels:
    #type: local
spec:
  #storageClassName: manual
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/shared/grafana"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pv-claim
spec:
  #storageClassName: manual
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
