#https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
#https://docs.k3s.io/storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildversionsapi-claim
  namespace: buildversions
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: buildversionsapi-volume
  namespace: buildversions
  labels:
    type: local
    app: buildversionsapi
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/shared/buildversionsapi"
